name: Publish-PSModule
description: Publish a PowerShell module to the PowerShell Gallery.
author: PSModule

inputs:
  Name:
    description: Name of the module to publish.
    required: false
  ModulePath:
    description: Path to the module to publish.
    required: false
    default: outputs/module
  APIKey:
    description: PowerShell Gallery API Key.
    required: true
  AutoCleanup:
    description: Control whether to automatically delete the prerelease tags after the stable release is created.
    required: false
    default: 'true'
  AutoPatching:
    description: Control whether to automatically handle patches. If disabled, the action will only create a patch release if the pull request has a 'patch' label.
    required: false
    default: 'true'
  IncrementalPrerelease:
    description: Control wether to automatically increment the prerelease number. If disabled, the action will ensure only one prerelease exists for a given branch.
    required: false
    default: 'true'
  DatePrereleaseFormat:
    description: If specified, uses a date based prerelease scheme. The format should be a valid .NET format string like 'yyyyMMddHHmm'.
    required: false
    default: ''
  VersionPrefix:
    description: The prefix to use for the version number.
    required: false
    default: v
  MajorLabels:
    description: A comma separated list of labels that trigger a major release.
    required: false
    default: major, breaking
  MinorLabels:
    description: A comma separated list of labels that trigger a minor release.
    required: false
    default: minor, feature
  PatchLabels:
    description: A comma separated list of labels that trigger a patch release.
    required: false
    default: patch, fix
  IgnoreLabels:
    description: A comma separated list of labels that do not trigger a release.
    required: false
    default: NoRelease
  ReleaseType:
    description: The type of release to create. Values are 'Release' (stable), 'Prerelease', or 'None'.
    required: false
    default: Release
  WhatIf:
    description: If specified, the action will only log the changes it would make, but will not actually create or delete any releases or tags.
    required: false
    default: 'false'
  WorkingDirectory:
    description: The working directory where the script will run from.
    required: false
    default: '.'
  UsePRTitleAsReleaseName:
    description: When enabled, uses the pull request title as the name for the GitHub release. If not set, the version string is used.
    required: false
    default: 'false'
  UsePRBodyAsReleaseNotes:
    description: When enabled, uses the pull request body as the release notes for the GitHub release. If not set, the release notes are auto-generated.
    required: false
    default: 'true'
  UsePRTitleAsNotesHeading:
    description: When enabled along with UsePRBodyAsReleaseNotes, the release notes will begin with the pull request title as a H1 heading followed by the pull request body. The title will reference the pull request number.
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Install-PSModuleHelpers
      uses: PSModule/Install-PSModuleHelpers@d60d63e4be477d1ca0c67c6085101fb109bce8f1 # v1.0.6

    - name: Update Microsoft.PowerShell.PSResourceGet
      shell: pwsh
      run: |
        Install-PSResource -Name Microsoft.PowerShell.PSResourceGet -Repository PSGallery -TrustRepository

    - name: Initialize Publish Context
      id: init
      shell: pwsh
      working-directory: ${{ inputs.WorkingDirectory }}
      env:
        PSMODULE_PUBLISH_PSMODULE_INPUT_Name: ${{ inputs.Name }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_AutoCleanup: ${{ inputs.AutoCleanup }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_AutoPatching: ${{ inputs.AutoPatching }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_DatePrereleaseFormat: ${{ inputs.DatePrereleaseFormat }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_IgnoreLabels: ${{ inputs.IgnoreLabels }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_ReleaseType: ${{ inputs.ReleaseType }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_IncrementalPrerelease: ${{ inputs.IncrementalPrerelease }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_MajorLabels: ${{ inputs.MajorLabels }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_MinorLabels: ${{ inputs.MinorLabels }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_PatchLabels: ${{ inputs.PatchLabels }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_VersionPrefix: ${{ inputs.VersionPrefix }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_WhatIf: ${{ inputs.WhatIf }}
      run: ${{ github.action_path }}/scripts/init.ps1

    - name: Download module artifact
      if: env.PUBLISH_CONTEXT_ShouldPublish == 'true' || inputs.WhatIf == 'true'
      uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
      with:
        name: module
        path: ${{ inputs.ModulePath }}

    - name: Publish Module
      if: env.PUBLISH_CONTEXT_ShouldPublish == 'true' || inputs.WhatIf == 'true'
      shell: pwsh
      working-directory: ${{ inputs.WorkingDirectory }}
      env:
        PSMODULE_PUBLISH_PSMODULE_INPUT_Name: ${{ inputs.Name }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_ModulePath: ${{ inputs.ModulePath }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_APIKey: ${{ inputs.APIKey }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_WhatIf: ${{ inputs.WhatIf }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_UsePRBodyAsReleaseNotes: ${{ inputs.UsePRBodyAsReleaseNotes }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_UsePRTitleAsReleaseName: ${{ inputs.UsePRTitleAsReleaseName }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_UsePRTitleAsNotesHeading: ${{ inputs.UsePRTitleAsNotesHeading }}
      run: ${{ github.action_path }}/scripts/publish.ps1

    - name: Cleanup Prereleases
      if: env.PUBLISH_CONTEXT_ShouldCleanup == 'true' || inputs.WhatIf == 'true'
      shell: pwsh
      working-directory: ${{ inputs.WorkingDirectory }}
      env:
        PSMODULE_PUBLISH_PSMODULE_INPUT_WhatIf: ${{ inputs.WhatIf }}
      run: ${{ github.action_path }}/scripts/cleanup.ps1
