name: Publish-PSModule (by PSModule)
description: Publish a PowerShell module to the PowerShell Gallery.
author: PSModule
branding:
  icon: upload-cloud
  color: gray-dark

inputs:
  Name:
    description: Name of the module to publish.
    required: false
  ModulePath:
    description: Path to the module to publish.
    required: false
    default: outputs/module
  APIKey:
    description: PowerShell Gallery API Key.
    required: true
  AutoCleanup:
    description: Control wether to automatically delete the prerelease tags after the stable release is created.
    required: false
    default: 'true'
  AutoPatching:
    description: Control wether to automatically handle patches. If disabled, the action will only create a patch release if the pull request has a 'patch' label.
    required: false
    default: 'true'
  IncrementalPrerelease:
    description: Control wether to automatically increment the prerelease number. If disabled, the action will ensure only one prerelease exists for a given branch.
    required: false
    default: 'true'
  DatePrereleaseFormat:
    description: If specified, uses a date based prerelease scheme. The format should be a valid .NET format string like 'yyyyMMddHHmm'.
    required: false
    default: ''
  VersionPrefix:
    description: The prefix to use for the version number.
    required: false
    default: v
  MajorLabels:
    description: A comma separated list of labels that trigger a major release.
    required: false
    default: major, breaking
  MinorLabels:
    description: A comma separated list of labels that trigger a minor release.
    required: false
    default: minor, feature
  PatchLabels:
    description: A comma separated list of labels that trigger a patch release.
    required: false
    default: patch, fix
  IgnoreLabels:
    description: A comma separated list of labels that do not trigger a release.
    required: false
    default: NoRelease
  WhatIf:
    description: If specified, the action will only log the changes it would make, but will not actually create or delete any releases or tags.
    required: false
    default: 'false'
  Debug:
    description: Enable debug output.
    required: false
    default: 'false'
  Verbose:
    description: Enable verbose output.
    required: false
    default: 'false'
  Version:
    description: Specifies the version of the GitHub module to be installed. The value must be an exact version.
    required: false
  Prerelease:
    description: Allow prerelease versions if available.
    required: false
    default: 'false'
  WorkingDirectory:
    description: The working directory where the script will run from.
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Install-PSModuleHelpers
      uses: PSModule/Install-PSModuleHelpers@v1

    - name: Run Publish-PSModule
      shell: pwsh
      working-directory: ${{ inputs.WorkingDirectory }}
      env:
        PSMODULE_PUBLISH_PSMODULE_INPUT_Name: ${{ inputs.Name }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_ModulePath: ${{ inputs.ModulePath }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_APIKey: ${{ inputs.APIKey }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_AutoCleanup: ${{ inputs.AutoCleanup }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_AutoPatching: ${{ inputs.AutoPatching }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_DatePrereleaseFormat: ${{ inputs.DatePrereleaseFormat }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_IgnoreLabels: ${{ inputs.IgnoreLabels }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_IncrementalPrerelease: ${{ inputs.IncrementalPrerelease }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_MajorLabels: ${{ inputs.MajorLabels }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_MinorLabels: ${{ inputs.MinorLabels }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_PatchLabels: ${{ inputs.PatchLabels }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_VersionPrefix: ${{ inputs.VersionPrefix }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_WhatIf: ${{ inputs.WhatIf }}
        PSMODULE_PUBLISH_PSMODULE_INPUT_WorkingDirectory: ${{ inputs.WorkingDirectory }}
      run: ${{ github.action_path }}/scripts/main.ps1
